### ISSUE TITLE
firewall rules dropdown box

### ISSUE THREAD

**Issue by devcose** [itworks99/pfsense-theme-gotham#1]
Hi nice theme.
however once you get past a certain amount of interfaces the firewall rules tab turns into a drop down box which for some reason does not have any of the css applied. so kind of makes the theme unusable. as the text is unreadable with the original dark theme.

Probably an easy fix if you have the time. 

Thanks

**Comment by itworks99** [comment]
I cannot reproduce; could you provide me with a screenshot please?

**Comment by devcose** [comment]
Seems they may of changed the behaviour . instead of turning into a drop down box the interfaces now go on to a second row. maybe at some point it still happens but it's fine for me now i guess 

Thanks for replying anyway
